set background=dark
if exists('g:colors_name')
hi clear
if exists('syntax_on')
syntax reset
endif
endif
let g:colors_name = 'lushwal'
highlight Normal guifg=#F5F5F5 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight! link User Normal
highlight Bold guifg=#F5F5F5 guibg=#0D0D0D guisp=NONE blend=NONE gui=bold
highlight Boolean guifg=#A7A9A7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Character guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight ColorColumn guifg=#C2C2C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Comment guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight Conceal guifg=#ABABAB guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight! link Whitespace Conceal
highlight Conditional guifg=#E6E6E6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Constant guifg=#A7A9A7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Cursor guifg=#0D0D0D guibg=#F5F5F5 guisp=NONE blend=NONE gui=NONE
highlight CursorColumn guifg=#C2C2C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight CursorLine guifg=NONE guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight CursorLineNr guifg=#F5F5F5 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight Debug guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Define guifg=#E6E6E6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Delimiter guifg=#AAACAA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticError guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticHint guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticInfo guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiagnosticUnderlineError guifg=#A0A2A0 guibg=NONE guisp=#A0A2A0 blend=NONE gui=underline
highlight DiagnosticUnderlineHint guifg=#F5F5F5 guibg=NONE guisp=#F5F5F5 blend=NONE gui=underline
highlight DiagnosticUnderlineInfo guifg=#CFCFCF guibg=NONE guisp=#CFCFCF blend=NONE gui=underline
highlight DiagnosticUnderlineWarn guifg=#B0B0B0 guibg=NONE guisp=#B0B0B0 blend=NONE gui=underline
highlight DiagnosticWarn guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight DiffAdd guifg=#A2A0A2 guibg=#ABABAB guisp=NONE blend=NONE gui=bold
highlight! link DiffAdded DiffAdd
highlight DiffChange guifg=#DBDBDB guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight DiffDelete guifg=#A0A2A0 guibg=#ABABAB guisp=NONE blend=NONE gui=bold
highlight! link DiffRemoved DiffDelete
highlight! link diffRemoved DiffDelete
highlight DiffFile guifg=#A0A2A0 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight DiffLine guifg=#CFCFCF guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight DiffNewFile guifg=#A2A0A2 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight DiffText guifg=#CFCFCF guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight Directory guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight EndOfBuffer guifg=#F5F5F5 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight Error guifg=#A0A2A0 guibg=#F5F5F5 guisp=NONE blend=NONE gui=NONE
highlight ErrorMsg guifg=#A0A2A0 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight Exception guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Float guifg=#A7A9A7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight FoldColumn guifg=#CFCFCF guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight Folded guifg=#F5F5F5 guibg=#ABABAB guisp=NONE blend=NONE gui=italic
highlight Function guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Identifier guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight IncSearch guifg=#ABABAB guibg=#A7A9A7 guisp=NONE blend=NONE gui=NONE
highlight Include guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Italic guifg=#F5F5F5 guibg=#0D0D0D guisp=NONE blend=NONE gui=italic
highlight Keyword guifg=#E6E6E6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Label guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight LineNr guifg=#DBDBDB guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight Macro guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MatchParen guifg=#F5F5F5 guibg=#DBDBDB guisp=NONE blend=NONE gui=NONE
highlight MiniCompletionActiveParameter guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniCursorword guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight! link MiniCursorwordCurrent MiniCursorword
highlight MiniIndentscopePrefix guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=nocombine
highlight MiniIndentscopeSymbol guifg=#ABABAB guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight MiniJump guifg=#CFCFCF guibg=NONE guisp=#DBDBDB blend=NONE gui=underline
highlight MiniJump2dSpot guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=undercurl
highlight MiniStarterCurrent guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterFooter guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterHeader guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniStarterInactive guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight MiniStarterItem guifg=#F5F5F5 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemBullet guifg=#AAACAA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterItemPrefix guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterQuery guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStarterSection guifg=#AAACAA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineDevinfo guifg=#F5F5F5 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFileinfo guifg=#F5F5F5 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineFilename guifg=#B0B0B0 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineInactive guifg=#C2C2C2 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeCommand guifg=#0D0D0D guibg=#F5F5F5 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeInsert guifg=#0D0D0D guibg=#CFCFCF guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeNormal guifg=#0D0D0D guibg=#A2A0A2 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeOther guifg=#0D0D0D guibg=#E6E6E6 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeReplace guifg=#0D0D0D guibg=#A0A2A0 guisp=NONE blend=NONE gui=NONE
highlight MiniStatuslineModeVisual guifg=#0D0D0D guibg=#A7A9A7 guisp=NONE blend=NONE gui=NONE
highlight MiniSurround guifg=#ABABAB guibg=#A7A9A7 guisp=NONE blend=NONE gui=NONE
highlight MiniTablineCurrent guifg=#DBDBDB guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniTablineFill guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MiniTablineHidden guifg=#A2A0A2 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedCurrent guifg=#F5F5F5 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedHidden guifg=#C2C2C2 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniTablineModifiedVisible guifg=#F5F5F5 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniTablineVisible guifg=#DBDBDB guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight MiniTestEmphasis guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestFail guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTestPass guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=bold
highlight MiniTrailspace guifg=#A0A2A0 guibg=#F5F5F5 guisp=NONE blend=NONE gui=NONE
highlight ModeMsg guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight MoreMsg guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight NonText guifg=#DBDBDB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Number guifg=#A7A9A7 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Operator guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PMenu guifg=#F5F5F5 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight PMenuSel guifg=#F5F5F5 guibg=#CFCFCF guisp=NONE blend=NONE gui=NONE
highlight PmenuSbar guifg=#C2C2C2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PmenuThumb guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight PreProc guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Question guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Repeat guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Search guifg=#DBDBDB guibg=#B0B0B0 guisp=NONE blend=NONE gui=NONE
highlight! link MiniTablineTabpagesection Search
highlight SignColumn guifg=#C2C2C2 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight Special guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialChar guifg=#AAACAA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpecialKey guifg=#DBDBDB guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight SpellBad guifg=#A0A2A0 guibg=NONE guisp=#A0A2A0 blend=NONE gui=underline
highlight SpellCap guifg=#B0B0B0 guibg=NONE guisp=#B0B0B0 blend=NONE gui=underline
highlight SpellLocal guifg=#F5F5F5 guibg=NONE guisp=#F5F5F5 blend=NONE gui=underline
highlight SpellRare guifg=#E6E6E6 guibg=NONE guisp=#E6E6E6 blend=NONE gui=underline
highlight Statement guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight StatusLine guifg=#F5F5F5 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight StatusLineNC guifg=#C2C2C2 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight StatusLineTerm guifg=#A2A0A2 guibg=#A2A0A2 guisp=NONE blend=NONE gui=NONE
highlight StatusLineTermNC guifg=#B0B0B0 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight StorageClass guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight String guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Structure guifg=#E6E6E6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight TabLine guifg=#DBDBDB guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight TabLineFill guifg=#DBDBDB guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight TabLineSel guifg=#A2A0A2 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight Tag guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Title guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight Todo guifg=#B0B0B0 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight TooLong guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Type guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Typedef guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight Underlined guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight VertSplit guifg=#F5F5F5 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight! link WinSeparator VertSplit
highlight Visual guifg=#0D0D0D guibg=#C2C2C2 guisp=NONE blend=NONE gui=NONE
highlight VisualNOS guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WarningMsg guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight WildMenu guifg=#F5F5F5 guibg=#CFCFCF guisp=NONE blend=NONE gui=NONE
highlight WinBar guifg=#F5F5F5 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight WinBarNC guifg=#C2C2C2 guibg=#0D0D0D guisp=NONE blend=NONE gui=NONE
highlight gitCommitOverflow guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight gitCommitSummary guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpCommand guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight helpExample guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @attribute guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @boolean guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @character.special guifg=#AAACAA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @comment guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @conditional guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.builtin guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constant.macro guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @constructor guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @debug guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @define guifg=#E6E6E6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @exception guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @field guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @float guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.builtin guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @function.macro guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @include guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword guifg=#E6E6E6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.function guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @keyword.operator guifg=#E6E6E6 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @label guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @method guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @namespace guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @none guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @number guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @operator guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @parameter guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @preproc guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @property guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.bracket guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.delimiter guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @punctuation.special guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @repeat guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @storageclass guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.escape guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.regex guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @string.special guifg=#AAACAA guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @symbol guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.attribute guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @tag.delimiter guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.bold guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.danger guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.diff.add guifg=#A2A0A2 guibg=#ABABAB guisp=NONE blend=NONE gui=bold
highlight @text.diff.delete guifg=#A0A2A0 guibg=#ABABAB guisp=NONE blend=NONE gui=bold
highlight @text.emphasis guifg=#E6E6E6 guibg=NONE guisp=NONE blend=NONE gui=italic
highlight @text.environment guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.environment.name guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.literal guifg=#A2A0A2 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.math guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.note guifg=#F5F5F5 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.reference guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @text.strike guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=strikethrough
highlight @text.title guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=bold
highlight @text.todo guifg=#B0B0B0 guibg=#ABABAB guisp=NONE blend=NONE gui=NONE
highlight @text.underline guifg=NONE guibg=NONE guisp=NONE blend=NONE gui=underline
highlight @text.uri guifg=NONE guibg=#ABABAB guisp=NONE blend=NONE gui=underline
highlight @type guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.builtin guifg=#CFCFCF guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @type.definition guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable guifg=#B0B0B0 guibg=NONE guisp=NONE blend=NONE gui=NONE
highlight @variable.builtin guifg=#A0A2A0 guibg=NONE guisp=NONE blend=NONE gui=NONE
